ATTEN=`caget -t SR-BI:01BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:01BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:01BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:01BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:01BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:01BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:01BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:01BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:02BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:02BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:03BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:03BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:04BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:04BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:05BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:05BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:06BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:06BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:07BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:07BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:08BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:08BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:09BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:09BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:10BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:10BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:11BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:11BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:12BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:12BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:13BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:13BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:14BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:14BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:15BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:15BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:16BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:16BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:17BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:17BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:18BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:18BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:19BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:19BPM7:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM1:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM1:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM2:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM2:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM3:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM3:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM4:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM4:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM5:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM5:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM6:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM6:CF:ATTEN_S $ATTEN
ATTEN=`caget -t SR-BI:20BPM7:CF:ATTEN_S`
ATTEN=`expr $ATTEN - $1`
caput SR-BI:20BPM7:CF:ATTEN_S $ATTEN
