#!/bin/sh
#
# Script to send command to all liberas or to a selection.

NAME_LIST="$(dirname "$(readlink -fn "$0")")/allbpms"

ASYNC='&'
WAIT=''
while getopts 'asl:r:wh' option; do
    case "$option" in
    a)  ASYNC='&' ;;
    s)  ASYNC=''  ;;
    l)  NAME_LIST="$OPTARG" ;;
    r)  LOG_EXT="$OPTARG"  ;;
    w)  WAIT='| cat' ;;
    h)  cat <<'EOF' 
Usage: liberas [-a] <pattern> [<command>]
Sends a command to all matching liberas.
    -a          send command asynchronously (the default)
    -s          send commands in sequence
    -l<list>    use specified list instead of default list
    -r<ext>     record all output in $BPM<ext> file
    -w          wait for all output to complete before exiting
EOF
        exit 0 ;;
    *)  echo >&2 'Invalid option: try -h for help'
        exit 1 ;;
    esac
done
shift $((OPTIND-1))
MATCH="$1"
shift

function Liberas()
{
    for BPM in $(grep -E "$MATCH" "$NAME_LIST"); do
        if [ -n "$LOG_EXT" ]; then
            LOGFILE=">'$BPM$LOG_EXT' 2>&1"
        else
            LOGFILE=
        fi
        eval 'ssh -x root@$BPM "$@"' $LOGFILE $ASYNC
    done
}

eval 'Liberas "$@"' $WAIT
